### ISSUE TITLE
xkbcommon failure

### ISSUE THREAD

**Issue by ericLemanissier** [qchateau/conan-center-bot#34]
currently, xkbcommon has the status "Error in system requirements"

1. do you think it's possible to add on https://qchateau.github.io/conan-center-bot/#/updatable a link to the CI run showing the error ?

by manually searching in CI logs, I found on https://github.com/qchateau/conan-center-bot/runs/1444844725#step:10:4378 that xkbcommon actually fails because `CONAN_SYSREQUIRES_MODE=verify`. This means that all recipes depending on xorg/system and opengl/system etc. will fail. 

2. do you think it's possible to set `CONAN_SYSREQUIRES_MODE=enabled` on your CI?

**Comment by qchateau** [comment]
Thanks for the tip, `CONAN_SYSREQUIRES_MODE=enabled` was easy enough.

I also added a link to the CI run, but you'll have to go through the logs yourself

**Comment by ericLemanissier** [comment]
thanks ! this tool, its UI and UX is impressive !

**Comment by qchateau** [comment]
> its UI and UX is impressive

Ahah, I hate UI and usually whatever UI I design has a shit UX, but recent JS frameworks do all the work for you as long as you keep it simple enough ;)
