### ISSUE TITLE
Website improvement: more data

### ISSUE THREAD

**Issue by madebr** [qchateau/conan-center-bot#36]
Adding more information to the table would be useful to decide the usefulness of an update.
- #commits since previous release (if available)
- days since last release
- age of new release
- ...

And finally, by changing the order of the table older or seldom updates can be ranked higher.

**Comment by madebr** [comment]
Great update!
The site feels very responsive too.

**Comment by madebr** [comment]
The number in the `current commit count` columns are a bit weird though.
Would it be possible to calculate the #of commits between the current and the new version tag?

**Comment by qchateau** [comment]
There are probably some corner cases, and obviously there's always some weird case (like a negative commit difference when branches diverge).

The big thing with this update is that I now have to clone the repository of every library. That's a bit time consuming but not excessive. On the plus side, we have access to all the information we want

**Comment by madebr** [comment]
Too bad github's api does not allow to get this information then.
It's nice to have 2 metrics for knowing how old a release is: time and number of commits.
These are actionable imho.

It would also be interesting to know, for `cci.YYYYMMDD` releases, how much the package has continued.
I would not add that information to the release table though.
