### ISSUE TITLE
Updatable tab on website is empty

### ISSUE THREAD

**Issue by madebr** [qchateau/conan-center-bot#38]
https://qchateau.github.io/conan-center-bot/#/updatable shows no table (25 November 2020, 5pm UC)

The dev console shows the following error:
```
TypeError: "e.current is undefined"
    e Updatable.vue:233
    selectedRecipes Updatable.vue:232
    VueJS 3
    render Updatable.vue:4
    VueJS 25
vue.esm.js:1897
```

(firefox 76.0)

**Comment by qchateau** [comment]
Ah yes, the CI is broken and it updated the site from a dev branch x)
