### ISSUE TITLE
ccb offers 'open pr' without testing valid configurations

### ISSUE THREAD

**Issue by prince-chrismc** [qchateau/conan-center-bot#43]
I got unlucky twice now https://github.com/conan-io/conan-center-index/pull/3705 and https://github.com/conan-io/conan-center-index/pull/3709

I think at a minimum it should try the PR at least one before appearing valid!

**Comment by qchateau** [comment]
What do you mean "try the PR" ? It already runs "conan create" with the latest hooks

**Comment by prince-chrismc** [comment]
Really?! dang you are good. I did not find where the result were posted... or what configuration(s) is ran... perhaps just note the information in the readme?

**Comment by qchateau** [comment]
It basically executes "conan create . @lib/x.x.x" on an ubuntu 20.04 image (provided by github actions) by almost default config (I think I just configure conan to use libstdc++11

I guess that information could be added to the website, let's leave this issue open as a reminder
