### ISSUE TITLE
Open PR links broke today

### ISSUE THREAD

**Issue by prince-chrismc** [qchateau/conan-center-bot#65]
https://github.com/null/null/pull/new/null

Idk what happened but the two latest recipes `mongo-c-driver` and another at the top (rest worked) give horrible URLs

![image](https://user-images.githubusercontent.com/16867443/125166566-352f3000-e16a-11eb-8017-56bcd2a8839e.png)

**Comment by qchateau** [comment]
I did 2 things:
I fixed bug in the frontend, such error should now display "Unknown error" and a backtrack
I reduced the concurrency of the update script, it may mitigate the root cause.
Please re-open if you see this again
