### ISSUE TITLE
enable dependabot

### ISSUE THREAD

**Issue by ericLemanissier** [qchateau/conan-center-bot#80]
it will automatically propose version bumps for dependencies, to help mitigate security issues.
cf https://github.com/ericLemanissier/conan-center-bot/pulls
and 
![image](https://user-images.githubusercontent.com/1926390/201090602-55386f6a-de8f-4632-af24-ba554a91df96.png)

You simply have to go to https://github.com/ericLemanissier/conan-center-bot/settings/security_analysisand enable the 3 dependabot switches

**Comment by qchateau** [comment]
I enabled the first two (security related) but not the third (version update) to limit the noise
