### ISSUE TITLE
Ignore recipes with deprecated attribute

### ISSUE THREAD

**Issue by SpaceIm** [qchateau/conan-center-bot#9]
For example jsonformoderncpp recipe can be excluded due to this attribute: https://github.com/conan-io/conan-center-index/blob/337f0cdc5cc51a3e2c66bb7bcc013ff1cff57d7e/recipes/jsonformoderncpp/all/conanfile.py#L15

**Comment by qchateau** [comment]
Ah nice, did not know about that.

That's 2 recipes removed !
